### ISSUE TITLE
Audio is not working

### ISSUE THREAD

**Issue by 0312birdzhang** [sailfish-on-ginkgo/main#13]

**Comment by foldfree** [comment]
hi, on the xda thread, someone is saying the audio works with theses vendor files

https://forum.xda-developers.com/t/shared-rom-sailfishos-4-x-experimental.4389001/#post-87080279

I am sorry I cannot test myself, I am using the rn8 as my main phone.

**Comment by 0312birdzhang** [comment]
sadly it's not working for me

**Comment by 0312birdzhang** [comment]
Fixed! As the vendor's audio config file has a typo, this is a fix https://github.com/sailfish-on-ginkgo/droid-config-ginkgo/commit/3f81574bc9e69c977d46125f7ee36e1e709952b4
