### ISSUE TITLE
One question, is there a more updated version of this good Port?

### ISSUE THREAD

**Issue by pachof** [sailfish-on-ginkgo/main#2]
I have been looking for Sailfish OS for my redmi note 8 for 5 months and I found this one, unfortunately it is in version 4.3 and it is very outdated and we compare it with the updated version 4.5 so you can update this very good Port, not only would I be grateful but all that time I was looking for would not be in vain

**Comment by 0312birdzhang** [comment]
Updated somedays ago, i will try to fix camera and waydroid.
