### ISSUE TITLE
I couldn't run waydroid

### ISSUE THREAD

**Issue by pachofonso** [sailfish-on-ginkgo/main#3]
I tried to run waydroid, but this appears in the log : " `(006789) [12:22:12] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- / init
(006789) [12:22:12] New background process: pid=21705, output=background
lxc-start: waydroid: utils.c: lxc_can_use_pidfd: 1772 Kernel does not support pidfds
lxc-start: waydroid: utils.c: safe_mount: 1198 Not a directory - Failed to mount "/dev/video" onto "/usr/lib64/lxc/rootfs/dev/video"
lxc-start: waydroid: utils.c: open_without_symlink: 1062 Too many levels of symbolic links - vibrator in /usr/lib64/lxc/rootfs/sys/class/leds/vibrator was a symbolic link!
(006789) [12:22:12] Save session config: /var/lib/waydroid/session.cfg
(006789) [12:22:13] Failed to add service waydroidhardware: -2147483647
(006789) [12:22:13] Failed to add service waydroidhardware: -2147483647
(021613) [12:22:13] Failed to start Clipboard manager service, check logs` "
and that appears: "`[22:21:48] Failed to get service waydroidplatform, trying again...`"

**Comment by 0312birdzhang** [comment]
You can try again now.  https://github.com/sailfish-on-ginkgo/main/blob/hybris16.0/README.md#how-to-install-waydroid

For me, replace aidl2 to aidl3 fixed it.

**Comment by 0312birdzhang** [comment]
https://github.com/sailfish-on-ginkgo/main/assets/1762041/7e3be858-b33f-42a7-ba39-b012dd79e474
